export const ropa = [
    {
        id: 0,
        image: "https://www.thefutbolstore.com.ar/uploads/v2/product/hi/725891_815_A.jpg",
        nombre: "Camiseta naranja",
        descripcion: "Excelente camiseta para hacer deporte",
        precio: 5000,
        stock: 9,
        categoria: "camiseta",
    },
    {
        id: 1,
        image: "https://www.thefutbolstore.com.ar/uploads/v2/product/hi/725891_739_A.jpg",
        nombre: "Camiseta amarilla",
        descripcion: "Excelente camiseta para hacer deporte",
        precio: 5000,
        stock: 10,
        categoria: "camiseta",
    },
    {
        id: 2,
        image: "https://www.thefutbolstore.com.ar/uploads/v2/product/hi/894230_010_A.jpg",
        nombre: "Camiseta negra",
        descripcion: "Excelente camiseta para hacer deporte",
        precio: 5000,
        stock: 10,
        categoria: "camiseta",
    },
    {
        id: 3,
        image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/cf2f4a8a-ba92-489f-b37d-ce50f3c21a7a/sportswear-tech-fleece-jogger-vSBPT5.png",
        nombre: "jogger negro",
        descripcion: "Excelente jogger para hacer deporte",
        precio: 5000,
        stock: 10,
        categoria: "pantalon",
    },
    {
        id: 4,
        image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/5d4b6aef-a9e8-43d4-b42e-5d30b4a0f7a1/sportswear-tech-fleece-jogger-9GJDns.png",
        nombre: "jogger naranja",
        descripcion: "Excelente jogger para hacer deporte",
        precio: 5000,
        stock: 10,
        categoria: "pantalon",
    },
    {
        id: 5,
        image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c8b7f156-e442-4ef0-9c4d-ea530fc59058/sportswear-club-jogger-de-tejido-fleece-PBVpKG.png",
        nombre: "jogger gris",
        descripcion: "Excelente jogger para hacer deporte",
        precio: 5000,
        stock: 10,
        categoria: "pantalon",
    },
];
